Update macsigning.yml

diff --git a/.github/workflows/macsigning.yml b/.github/workflows/macsigning.yml
--- a/.github/workflows/macsigning.yml
+++ b/.github/workflows/macsigning.yml
@@ -56,12 +56,12 @@ jobs:
     - name: Sign the binary before packing DMG
       shell: bash
       run: |
-        /usr/bin/codesign --force --verify --deep --verbose -s "Lancelot Software, LLC (L65255N3F7)" -v "filesToSign/chef-node-management-cli"
+        /usr/bin/codesign --force --verify --deep --verbose --sign "Lancelot Software, LLC (L65255N3F7)" --options runtime -v "filesToSign/chef-node-management-cli"
 
-    - name: Create, sign the DMG
+    - name: Create, sign, notarize, and staple the DMG
       id: create-dmg
       run: |
-        create-dmg --volname "${{env.PRODUCT_READABLE_NAME}} Application Installer" --background "chef-courier-installer-background.png" --codesign "${{env.MACOS_CERTIFICATE_NAME}}" "${{env.MACOS_DMG_FILENAME}}" "filesToSign/"
+        create-dmg --volname "${{env.PRODUCT_READABLE_NAME}} Application Installer" --background "chef-courier-installer-background.png" --codesign "${{env.MACOS_CERTIFICATE_NAME}}" --notarize ${{env.NOTARYTOOL_CREDENTIAL_NAME}} "${{env.MACOS_DMG_FILENAME}}" "filesToSign/"
 
     # Default software on the runner here https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md
     # all runners listed here https://github.com/actions/runner-images
@@ -76,73 +76,73 @@ jobs:
     #     keychain_profile: '${{env.NOTARYTOOL_CREDENTIAL_NAME}}'
     #     xcode_path: '/Applications/Xcode_15.4.app'
 
-    - name: Full manual run
-      run: |
-        request_uuid=""
+    # - name: Full manual run
+    #   run: |
+    #     request_uuid=""
 
-        function notarize_file() {
-          request_uuid=$(xcrun notarytool submit "${{env.MACOS_DMG_FILENAME}}" \
-                                          --output-format json \
-                                          --team-id "${{env.APPLE_TEAM_ID}}" \
-                                          --apple-id "${{steps.akeyless.outputs.APPLE_ACCOUNT_EMAIL}}" \
-                                          --password "${{steps.akeyless.outputs.APPLE_ACCOUNT_APP_SPECIFIC_PASSWORD}}" 2>&1 \
-                          | jq -r '.id')
+    #     function notarize_file() {
+    #       request_uuid=$(xcrun notarytool submit "${{env.MACOS_DMG_FILENAME}}" \
+    #                                       --output-format json \
+    #                                       --team-id "${{env.APPLE_TEAM_ID}}" \
+    #                                       --apple-id "${{steps.akeyless.outputs.APPLE_ACCOUNT_EMAIL}}" \
+    #                                       --password "${{steps.akeyless.outputs.APPLE_ACCOUNT_APP_SPECIFIC_PASSWORD}}" 2>&1 \
+    #                       | jq -r '.id')
 
-          echo "${request_uuid}:${{env.MACOS_DMG_FILENAME}}"
+    #       echo "${request_uuid}:${{env.MACOS_DMG_FILENAME}}"
 
-          if [[ $request_uuid == "" ]]; then 
-            echo "Could not upload for notarization ${{env.MACOS_DMG_FILENAME}}"
-            exit 1
-          fi
-        }
+    #       if [[ $request_uuid == "" ]]; then 
+    #         echo "Could not upload for notarization ${{env.MACOS_DMG_FILENAME}}"
+    #         exit 1
+    #       fi
+    #     }
 
-        function request_status() {
-          req_status=$(xcrun notarytool info "$request_uuid" \
-                                        --output-format json \
-                                        --team-id "${{env.APPLE_TEAM_ID}}" \
-                                        --apple-id  "${{steps.akeyless.outputs.APPLE_ACCOUNT_EMAIL}}" \
-                                        --password "${{steps.akeyless.outputs.APPLE_ACCOUNT_APP_SPECIFIC_PASSWORD}}" 2>&1 \
-                      | jq -r '.status')
-          echo "$req_status"
-        }
+    #     function request_status() {
+    #       req_status=$(xcrun notarytool info "$request_uuid" \
+    #                                     --output-format json \
+    #                                     --team-id "${{env.APPLE_TEAM_ID}}" \
+    #                                     --apple-id  "${{steps.akeyless.outputs.APPLE_ACCOUNT_EMAIL}}" \
+    #                                     --password "${{steps.akeyless.outputs.APPLE_ACCOUNT_APP_SPECIFIC_PASSWORD}}" 2>&1 \
+    #                   | jq -r '.status')
+    #       echo "$req_status"
+    #     }
 
-        function wait_for_noterize() {
-          # wait for status to be not "in progress" any more
-          status="In Progress"
-          while [[ "$status" == "In Progress" ]]; do
-            echo -n "Waiting on ${request_uuid}..."
-            sleep 10
-            status=$(request_status)
-            echo "Current status check: $status"
-          done
+    #     function wait_for_noterize() {
+    #       # wait for status to be not "in progress" any more
+    #       status="In Progress"
+    #       while [[ "$status" == "In Progress" ]]; do
+    #         echo -n "Waiting on ${request_uuid}..."
+    #         sleep 10
+    #         status=$(request_status)
+    #         echo "Current status check: $status"
+    #       done
 
-          xcrun notarytool info "$request_uuid" \
-                                --output-format json \
-                                --team-id "${{env.APPLE_TEAM_ID}}" \
-                                --apple-id  "${{steps.akeyless.outputs.APPLE_ACCOUNT_EMAIL}}" \
-                                --password "${{steps.akeyless.outputs.APPLE_ACCOUNT_APP_SPECIFIC_PASSWORD}}" 2>&1 \
-              | jq '.'
+    #       xcrun notarytool info "$request_uuid" \
+    #                             --output-format json \
+    #                             --team-id "${{env.APPLE_TEAM_ID}}" \
+    #                             --apple-id  "${{steps.akeyless.outputs.APPLE_ACCOUNT_EMAIL}}" \
+    #                             --password "${{steps.akeyless.outputs.APPLE_ACCOUNT_APP_SPECIFIC_PASSWORD}}" 2>&1 \
+    #           | jq '.'
 
-          if [[ $status != "Accepted" ]]; then
-            error_details=$(xcrun notarytool log "$request_uuid" \
-                                  --output-format json \
-                                  --team-id "${{env.APPLE_TEAM_ID}}" \
-                                  --apple-id  "${{steps.akeyless.outputs.APPLE_ACCOUNT_EMAIL}}" \
-                                  --password "${{steps.akeyless.outputs.APPLE_ACCOUNT_APP_SPECIFIC_PASSWORD}}" 2>&1 \
-                | jq '.')
+    #       if [[ $status != "Accepted" ]]; then
+    #         error_details=$(xcrun notarytool log "$request_uuid" \
+    #                               --output-format json \
+    #                               --team-id "${{env.APPLE_TEAM_ID}}" \
+    #                               --apple-id  "${{steps.akeyless.outputs.APPLE_ACCOUNT_EMAIL}}" \
+    #                               --password "${{steps.akeyless.outputs.APPLE_ACCOUNT_APP_SPECIFIC_PASSWORD}}" 2>&1 \
+    #             | jq '.')
 
-            echo "::error An error occurred trying to notarize ${{env.MACOS_DMG_FILENAME}}. $error_details"
+    #         echo "::error An error occurred trying to notarize ${{env.MACOS_DMG_FILENAME}}. $error_details"
                 
-            exit 1
-          fi
+    #         exit 1
+    #       fi
 
-          echo "Stapling the ${{env.MACOS_DMG_FILENAME}}"
-          xcrun stapler staple "${{env.MACOS_DMG_FILENAME}}"
-        }
+    #       echo "Stapling the ${{env.MACOS_DMG_FILENAME}}"
+    #       xcrun stapler staple "${{env.MACOS_DMG_FILENAME}}"
+    #     }
 
-        notarize_file
+    #     notarize_file
 
-        wait_for_noterize
+    #     wait_for_noterize
 
 
     - name: Confirm DMG exists
